# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccca6a0775c7f60c19381cfcaae7a097f1bae3ebf9938b3b4422e8027550be65361106040cdc9965a7e494f51f591e38a099c1d39ad1d48dd3dac8d512a045e0

test:
  secret_key_base: b1fc2ace1a9f57562cfb38c1343ab5dff002cdb9f0c6578936856107ffcf599b51ea65e509cefb875992a017289ffbf2daf78baa5356b173dab75af3d73ebb1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
